@startuml
skinparam classAttributeIconSize 0

!include domain-collection-group.puml
!include domain-contributors.puml
!include domain-edition.puml
!include domain-media-copy.puml
!include domain-media-work.puml

@enduml
