@startuml
skinparam classAttributeIconSize 0

' ===== CORE =====
class MediaWork <<AggregateRoot>> {
    +Id: UUID
    +Title: string
    +Description?: string
    +OriginalReleaseDate: LocalDate
    -_structure: MediaStructure
    -_contributions: List<Contribution>
    -_content: List<Content>
    --
    +AddContribution(id, role): void
    +RemoveContribution(id): void
    +AddContent(content): void
    +RemoveContent(id): void
}

note top of MediaWork
Invariant:
- Must have exactly one MediaStructure
- Structure defines the MediaWork type
- Must have at least one creator contribution
- Cannot remove last creator
- All Features / Episodes must reference a
  Content that is a PlayableContent inside
  MediaWork._contents
end note

abstract class MediaStructure <<Entity>> {
    --
    +Type(): MediaWorkType
    +IsCreatorRole(role): bool
}

MediaWork "1" *-- "1" MediaStructure

enum MediaWorkType {
    Movie
    TV
}

' ===== CONTRIBUTIONS =====
class Contribution <<Entity>> {
    +Id: UUID
    +ContributorId: UUID
    +ContributorRole: ContributorRole
}

class ContributorRole <<ValueObject>> {
    +Name: string
}

MediaWork "1" *-- "1..*" Contribution

' ===== CONTENT =====
class Content <<Entity>> {
    +Id: UUID
    +Title?: string
    +Description?: string
}

MediaWork "1" *-- "0..*" Content

class PlayableContent {
    +RuntimeMinutes: int
    +CutType?: CutType
    +SubtitleTracks: List<string>
}

enum CutType {
    DirectorCut
    Extended
    FinalCut
    HomeRelease
    International
    Original
    Other
    Theatrical
    Uncut
}

Content <|-- PlayableContent

class AudioTrack <<ValueObject>> {
    +Language: string
    +Format: string
}

PlayableContent "1" *-- "0..*" AudioTrack

' ===== MOVIE =====
class MovieStructure {
    -_features: List<UUID>
    --
    +AddFeature(id): void
    +RemoveFeature(id): void
}

MediaStructure <|-- MovieStructure
MovieStructure ..> PlayableContent

' ===== TV =====
class TVStructure {
    +Status: TVStatus
    +EndedOn?: LocalDate
    -_seasons: List<UUID>
    --
    +AddSeason(id): void
    +RemoveSeason(id): void
    +AddEpisodeToSeason(seasonId, episodeId, number?, airDate, role?)
    +RemoveEpisodeFromSeason(seasonId, episodeId)
}

MediaStructure <|-- TVStructure

enum TVStatus {
    Ongoing
    Ended
    Cancelled
    Unknown
}

class Season <<Entity>> {
    +Id: UUID
    +SeasonNumber: int
    +Title: string?
    +Description: string?
    _episodes: List<Episode>
    --
    +AddEpisode(id, number, airDate, role)
    +RemoveEpisode(id)
}

TVStructure "1" *-- "1..*" Season

class Episode <<Entity>> {
    +contentId: UUID
    +EpisodeNumber?: int
    +AirDate: LocalDate
    +EpisodeRole?: EpisodeRole;
}

Season "1" *-- "1..*" Episode
Episode ..> PlayableContent

enum EpisodeRole {
    Regular
    Bonus
    Special
}

' ===== CROSS-AGGREGATE REFERENCE =====
Contribution ..> Contributor

@enduml
